### ISSUE TITLE
Prod build failed

### ISSUE THREAD

**Issue by vasyliv** [MarkPieszak/aspnetcore-angular2-universal#460]
step to reproduce 
download the project from branch "master"
npm install
npm run build:prod
has the next bug
![image](https://user-images.githubusercontent.com/19407350/32408285-41a0fda4-c19e-11e7-98f1-a889d0c6b77b.png)

the regexp should be as this one
![image](https://user-images.githubusercontent.com/19407350/32408291-5959a78e-c19e-11e7-918a-8daa6b93d15b.png)

how can i skip minimization for current regexp?

**Comment by alexbenitez** [comment]
I have the same problem when deploying to my web hosting provider (the Angular 4 version runs OK in the same server).                   

See: "...Prerendering failed because of error: SyntaxError: Invalid regular expression: /^[_A-Za- ...  ". Including error and part of the stack trace below:            
         
         
            Hosting environment: Production
            Content root path: C:\ClientSites\aztectechnologies.net\paroissesaintremi.online
            Now listening on: http://localhost:27973
            Application started. Press Ctrl+C to shut down.
            info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]

                at Object.create.location.get (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1542:16379)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.<anonymous> (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1030:27089)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.exports.isValidName (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1542:2523)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.module.exports (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1091:2699)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.module.exports (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1939:412)
            Current directory is: C:\ClientSites\aztectechnologies.net\paroissesaintremi.online

            at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)      Request starting HTTP/1.1 GET http://paroissesaintremi.online/  
            info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
                Executing action method AspCoreServer.Controllers.HomeController.Index (Asp2017) with arguments ((null)) - ModelState is Valid
            info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
                Executed action AspCoreServer.Controllers.HomeController.Index (Asp2017) in 1924.9405ms
            fail: Microsoft.AspNetCore.Server.Kestrel[13]
                Connection id "0HL941CASFAVL", Request id "0HL941CASFAVL:00000001": An unhandled exception was thrown by the application.
            Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Prerendering failed because of error: SyntaxError: Invalid regular expression: /^[_A-Za-zA-�O-�o-??-??-??-?�-??-??-??-??-??-??-?:][-._A-Za-z0-9�A-�O-�o-?`-??-?????�-??-??-??-??-??-??-?:]*$/: Range out of order in character class
                at RegExp (native)
                at Object.create.location.get (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1542:16379)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.<anonymous> (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1030:27089)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.exports.isValidName (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1542:2523)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.module.exports (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1091:2699)
                at __webpack_require__ (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1:355)
                at Object.module.exports (C:\ClientSites\aztectechnologies.net\paroissesaintremi.online\ClientApp\dist\main-server.js:1939:412)
            Current directory is: C:\ClientSites\aztectechnologies.net\paroissesaintremi.online

            at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by arlenniu** [comment]
vs2017 run iis error:

An error occurred while starting the application.

AggregateException: One or more errors occurred. (Cannot find module './wwwroot/dist/vendor-manifest.json'
Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at module.exports (F:\test\aspnetcore-angular2-universal\webpack.config.js:51:27)
at createWebpackDevServer (F:\test\aspnetcore-angular2-universal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:194:31)
at createWebpackDevServer (C:\Users\arlen\AppData\Local\Temp\bruj3kay.nrv:74:50)
at C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:114:19
at IncomingMessage.<anonymous> (C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:133:38)
at emitNone (events.js:86:13))
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)

NodeInvocationException: Cannot find module './wwwroot/dist/vendor-manifest.json'
Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at module.exports (F:\test\aspnetcore-angular2-universal\webpack.config.js:51:27)
at createWebpackDevServer (F:\test\aspnetcore-angular2-universal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:194:31)
at createWebpackDevServer (C:\Users\arlen\AppData\Local\Temp\bruj3kay.nrv:74:50)
at C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:114:19
at IncomingMessage.<anonymous> (C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:133:38)
at emitNone (events.js:86:13)
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

AggregateException: One or more errors occurred. (Cannot find module './wwwroot/dist/vendor-manifest.json'
 Error: Cannot find module './wwwroot/dist/vendor-manifest.json' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at module.exports (F:\test\aspnetcore-angular2-universal\webpack.config.js:51:27) at createWebpackDevServer (F:\test\aspnetcore-angular2-universal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:194:31) at createWebpackDevServer (C:\Users\arlen\AppData\Local\Temp\bruj3kay.nrv:74:50) at C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:114:19 at IncomingMessage.<anonymous> (C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:133:38) at emitNone (events.js:86:13))
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
AspCoreServer.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, SpaDbContext context) in Startup.cs
+
        app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter+<>c__DisplayClass0_1.<Configure>b__0(IApplicationBuilder builder)
Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Show raw exception details
NodeInvocationException: Cannot find module './wwwroot/dist/vendor-manifest.json'
 Error: Cannot find module './wwwroot/dist/vendor-manifest.json' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at module.exports (F:\test\aspnetcore-angular2-universal\webpack.config.js:51:27) at createWebpackDevServer (F:\test\aspnetcore-angular2-universal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:194:31) at createWebpackDevServer (C:\Users\arlen\AppData\Local\Temp\bruj3kay.nrv:74:50) at C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:114:19 at IncomingMessage.<anonymous> (C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:133:38) at emitNone (events.js:86:13)
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()

Show raw exception details
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Cannot find module './wwwroot/dist/vendor-manifest.json'
Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (F:\test\aspnetcore-angular2-universal\webpack.config.js:51:27)
    at createWebpackDevServer (F:\test\aspnetcore-angular2-universal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:194:31)
    at createWebpackDevServer (C:\Users\arlen\AppData\Local\Temp\bruj3kay.nrv:74:50)
    at C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:114:19
    at IncomingMessage.<anonymous> (C:\Users\arlen\AppData\Local\Temp\i4jdk5mx.zmu:133:38)
    at emitNone (events.js:86:13)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()

**Comment by MarkPieszak** [comment]
I’ll take a look tomorrow! Must of forgotten to update something there for prod builds... 
if anyone finds out what it is, let us know!

**Comment by arlenniu** [comment]
Thank you!
I also found that the error: (Error: SyntaxError: Invalid regular expression: / ^), I use Chrome to refresh the page, the page is successful;
But AggregateException: One or more errors occurred. (Can not find module './wwwroot/dist/vendor-manifest.json', I use Chrome to refresh the page, unsuccessfully.
As a beginner, do not know the details of ng5.0universal change @nguniversal; @ angular / platform-server and so on.
I compare GIT history, did not find package.json and webpack.config.vendor.js, the package conflict or missing something.
Summary: debug mode successful, release mode unsuccessful. vs2017 posted to AZURE, debug and release, are http500;

**Comment by consigliory** [comment]
looks like I have related issue. On production build in chrome it throw this error:
main-client.js:299 Uncaught SyntaxError: Invalid regular expression: /^[_A-Za-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌-‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:][-._A-Za-z0-9·À-ÖØ-öø-˿̀-ͽͿ-῿‌‍‿⁀⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:]*$/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.<anonymous> (main-client.js:299)
    at t (main-client.js:1)
    at Object.<anonymous> (main-client.js:226)
    at t (main-client.js:1)
    at Object.<anonymous> (main-client.js:299)
    at t (main-client.js:1)
    at Object.<anonymous> (main-client.js:226)
    at t (main-client.js:1)
    at Object.<anonymous> (main-client.js:431)

**Comment by etatuev** [comment]
Same here, seems that some issues occurred during minification, Commenting out of UglifyJS plugin fixing this.

**Comment by alexbenitez** [comment]
Hi statuev,

I think that I tried the same but likely I deployed the wrong package (I got the same error). I tried many ad-hoc things. Do you mind copy and pasting the lines that you commented out so I can give it a try? Is this in the webpack configuration?

**Comment by ElSenorJuju** [comment]
Same issue on build:prod, i've tried to comment uglyfy without any result.

**Comment by etatuev** [comment]
I'm using slightly modified version of this package for my own project, so maybe there was something more. I'll try to repeat steps for exactly this package. However, after resolving I've got new strange issue (only for server-side render)  - ENONENT  'project_root_folder/my-component.view.html'

**Comment by ElSenorJuju** [comment]
This is exactly what i have when i comment uglyfy. Server side can't find a component.

**Comment by alexbenitez** [comment]
Yep... that's what I got without uglyfy.  The Starter as is does not work in Prod mode.

**Comment by bigWebApps** [comment]
Hi,

yea. there is uglyfy

UglifyJS unescapes \u0000 and other unicode char code strings and converts them . this results in some libraries (eg,js-base64,firebase) getting screwed up, and Chrome refusing to load the extension b/c theinjectionisn'tutf-8`.

I had a similar problem and it happened because I'm using WebPack's uglify which does the compression of unicode characters to UTF-8 and the server wasn't specifying UTF-8 as the charset causing the browser to fail to properly parse it. (https://github.com/lodash/lodash/issues/2625)

need to set output: {
                    ascii_only: true,
                   beautify: false,
           }(https://github.com/zalmoxisus/crossbuilder/commit/6c70ff4650efd346211c221d97390a143cf5ef8e)

also I noticed we use 0.4.6, and 1.0.0 version

Eugene

**Comment by alexbenitez** [comment]
I tried replacing Uglify with the following (as per https://github.com/lodash/lodash/issues/2625) but unfortunately I get the error below:              

             ... app.component.html' . Error: ENOENT: no such file or directory, open             

               // uglify setting
                new webpack.optimize.UglifyJsPlugin({
                comments: false,
                compress: {
                  warnings: false
                },
                 output: {
                            ascii_only: true,
                            beautify: false,
                    }
              })

Hopefully someone finds and a solution. The starter is not very useful if it can't be deployed...

**Comment by GetTaxSolutions** [comment]
We also have the same problem. When comment this code it is working but it's not solution. May be the problem is in this plugin?:
```
//new webpack.optimize.UglifyJsPlugin({
//             compress: false,
//             mangle: false
//            }),
```

**Comment by MarkPieszak** [comment]
Seems like uglify is giving us problems, this is real strange... I’ll post back here when I know more! 

Apologies everyone 😔

**Comment by LiverpoolOwen** [comment]
Any workaround for this? commenting out UglifyJsPlugin just left me with another error

**Comment by husseinjahan** [comment]
Any workaround @MarkPieszak ?

**Comment by MarkPieszak** [comment]
So a few updates, I'm still looking into it, and there seems to be an issue with Uglify, but actually you can remove that (realistically) from the server build, as it doesn't get "loaded" (since it is used outside of the browser), so minifying it, doesn't benefit in any way.

So the other problem `ENOENT: no such file or directory, open 'app.component.html'` seems to be coming from `angular2-template-loader` not doing its thing. Since it should be **inlining** the template, since we're not trying to load it here.

I'll keep looking, just wanted to give an update!

**Comment by bigWebApps** [comment]
problem with line 259 in main-server.js
a="_A-Za-z\xc0-\xd6\xd8-\xf6\xf8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd",u="-._A-Za-z0-9\xb7\xc0-\xd6\xd8-\xf6\xf8-\u02ff\u0300-\u037d\u037f-\u1fff\u200c\u200d\u203f\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd"

I updated "webpack": "^3.8.1",
"file-loader": "^1.1.5",
"extract-text-webpack-plugin": "^3.0.2",

now uglify recognize ascii_only

so I can do 

new webpack.optimize.UglifyJsPlugin({
              output: {
                ascii_only: true,
                beautify: false,
              }
            }),

js files now CORRECT, no unicode strings

BUT error ENOENT: no such file or directory, open 'app.component.html'
still exists

**Comment by bigWebApps** [comment]
also on production we use 

@ngtools/webpack - NOT angular2-template-loader

line 34 in webpack.config.js
 use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] : '@ngtools/webpack'

**Comment by bigWebApps** [comment]
strange but error shows that  app.component.html looked in roor folder, not ClientApp folder
----
NodeInvocationException: ENOENT: no such file or directory, open 'C:\__WORK\aspnetcore-angular2-universal\app.component.html'
Error: ENOENT: no such file or directory, open 'C:\__WORK\aspnetcore-angular2-universal\app.component.html'

**Comment by michaelbenavi** [comment]
Hi,

i'm really desperate...
I'm working with the new starter :  *NEW* Angular 5.x Universal & ASP.NET Core 2.0 Advanced Starter.
On Dev it's working just fine and also "Dotnet Publish" received no errors, 
but after uploading it to an IIS site (i set the app pool to No managed code) i got "This page isn’t working" error 500, on the stdout log file i get 

"Connection id "0HL9F9S8N9DAS", Request id "0HL9F9S8N9DAS:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Prerendering failed because of error: SyntaxError: Invalid regular expression: /^[_A-Za-zA-?O-?o-??-??-??-?ר-??-??-??-??-??-??-?:][-._A-Za-z0-9תA-?O-?o-?`-??-?????ר-??-??-??-??-??-??-?:]*$/: Range out of order in character class"

please Helllllp me, i need to go to UAT env but it wont work.

Thanks,
Michael.

**Comment by richdafunk** [comment]
@michaelbenavi: I had the same problem. Try right clicking your project and choose edit project file. Add this line inside all the <propertygroup> elements:

<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>

Now publish will include all binary files.

**Comment by netbidev** [comment]
I have also this problem.

**Comment by MarkPieszak** [comment]
We’re still working out the kinks guys apologies! It was my fault for releasing 5.x and not releasing Prod was broken.

**Comment by LiverpoolOwen** [comment]
Hello @MarkPieszak, do we have any idea how long this will take to fix? Thanks

**Comment by MaklaCof** [comment]
I also have problems, because SignalRCore (@aspnet/signalr-client) does not compile. Details [are here](https://github.com/aspnet/SignalR/issues/867#issuecomment-329114305).

**Comment by svoychik** [comment]
I have the same problem. Are there any updates? 
![capture](https://user-images.githubusercontent.com/7015817/33422835-9b143042-d5bf-11e7-8a1f-5d50746b6193.PNG)

**Comment by stephenlautier** [comment]
the initial issue posted in this thread, is caused by uglifyjs

```
SyntaxError: Invalid regular expressions...
```

and that can be fixed by using the new uglifyjs plugin https://github.com/webpack-contrib/uglifyjs-webpack-plugin

However after fixing that, there's another issue which is the following:

```
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: No NgModule metadata found for 'AppModule'.
Error: No NgModule metadata found for 'AppModule'.
```

Anyone managed to fixed this or knows why exactly it happens?
So far the only workaround in order to get this "working", is the disable AoT for SSR, because the error only happens when its AoT + SSR

**Comment by MarkPieszak** [comment]
Sorry it's been a nightmare everyone - time has not been on my side and I've been unbelievably busy - but I'm trying to have this fixed as soon as I can, even if it kills me 🗡 🤕

I've reverted the repo back to Angular 4.x for the time being, so everyone else doesn't run into these issues, and I pushed up the 5.0 work into a branch, where SSR is disabled for the time being until everything is up and running. https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/angular-5.0-WIP

Hope to post back soon when I have that one figured out and I'll merge it back into Master! :(

**Comment by vasyliv** [comment]
```
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: No NgModule metadata found for 'AppModule'.
Error: No NgModule metadata found for 'AppModule'.
```
this a bug with @nguniversal/aspnetcore-engine, the module can not resolve a module, without SSR all work well.

**Comment by yanivamrami** [comment]
Hi,
Any news with this issue? I encounter the problem when I run 'dotnet publish' or 'dotnet publish -c Release'.
In both cases, my main-server.js gets minified and the publish process runs successfully, but I fail to run the web site (either in dev nor in production) with the same error above. My workaround is to replace the minified file with the un-minified one (which luckily I backed up).

Appreciate if you could provide a solution...

Thank you!

**Comment by Adondriel** [comment]
@yanivamrami Are you trying to build for angular 5? If so, I don't believe any progress has been made just yet.

**Comment by yanivamrami** [comment]
@Adondriel  yes, I am trying to build for Angular 5...

Meanwhile, I think I found a solution.
I have changed my webpack.config.js to match this one: https://github.com/MarkPieszak/aspnetcore-angular2-universal from GitHub (thanks to Mark).

Then, I have made the following 2 changes:
In index.cshtml:
change from 
`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app> `
to `<app>Loading...</app>` (or whatever you want your server to show while loading the page), 
and in boot.server.ts change from: 
`const zone = moduleRef.injector.get(NgZone); `
to `const zone: NgZone = moduleRef.injector.get(NgZone);`

I than ran the 'dotnet publish -c Release'. The public process finished successfully, the main-server.js was minified but working...!

Hope this would be beneficial to anyone here.

Yaniv

**Comment by Adondriel** [comment]
Awesome! If I get time, I may try to put it in a PR into the 5.0 branch,
but don't hold your breath for me, cause I'm gunna be busy for a while
starting here soon.

**Comment by odahcam** [comment]
@yanivamrami sorry, but I could not understand how you solved the problem, my Index.cshtml does not have any `<app>` tag and my `boot.server.ts` does not have any `const zone`.

Can you help me to understand the proccess?

**Comment by yanivamrami** [comment]
@odahcam  maybe that is the problem?
could you please post both files?

**Comment by peterdobson** [comment]
@odahcam , the solution @yanivamrami is suggesting will remove Server Side Rending functionality. Can you do without SSR? For many one of the main benefits of this template is the SSR.

**Comment by odahcam** [comment]
Understood, I want server-side rendering, so I will keep working on it.

**Comment by MarkPieszak** [comment]
For now 5.0 has been merged into master, but UglifyJSPlugin is having some major issues (so it's been removed for now).

We won't have these problems once we merge into the CLI-based template, so I'll close this out for now!

**Comment by guillep2k** [comment]
In my case,  @yanivamrami 's solution worked great. I still don't know what SSR is, so for starters I can at least publish my site in the local network for others to see. Some other time I'll investigate if I need better options.

**Comment by mario-tiscareno** [comment]
@etatuev I tried your fix. Indeed it fixes the SyntaxError but during runtime I'm still getting:

`NodeInvocationException: No NgModule metadata found for 'AppModule'`

You mentioned this should work with SSR and AoT but I'm not seeing it. Do you think I'm missing something?

Thanks

**Comment by etatuev** [comment]
@mario-tiscareno It's separate issue, which was already fixed in this repo by using separate `boot.server.ts` file for production build. It's currently named `boot.server.PRODUCTION.ts` here, and you can find how it used in webpack configuration. The main difference is that line 
`const { AppModuleNgFactory } = require('./app/app.module.server.ngfactory');` 
As you can see, instead of just usual import of `app.module`, we're injecting module factory, which was created by angular compiler during AoT. As far as I understand, this is related to some issues in Angular Universal lib for .NET Core, i think @MarkPieszak knows much more.

**Comment by mario-tiscareno** [comment]
I see now. I was missing the webpack change. I'll try it out.
Thanks for the super-quick response @etatuev !

**Comment by mario-tiscareno** [comment]
Everything is working fine now. Thanks!

**Comment by etatuev** [comment]
You're welcome :)

**Comment by pavel-agarkov** [comment]
Hello,
I have a similar setup with Asp.Net Core + Angular + SSR
After updating to Angular 5 I started receiving the same "Invalid regular expression" error.
I have tried all the methods from [#20109](https://github.com/angular/angular/issues/20109)
Updated webpack from 2.5.1->3.8.1->3.11.0
Changed webpack.config.js the same way as @etatuev did.
But I still have the error.
Even if I completely comment UglifyJsPlugin - I still have it!
Probably AngularCompilerPlugin still does uglification by itself no matter what.
Do you have any ideas what else can I try?

I have:
```
node: "6.11.0"
"@angular/...": "5.2.10"
"webpack": "3.11.0"
"@ngtools/webpack": "1.10.2"
```

webpack.config.js:
```js
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;

module.exports = (env) => {
    // Configuration in common to both client-side and server-side bundles
    const isDevBuild = !(env && env.prod);
    const isTest = process.env.NODE_ENV === 'test';
    const clientBundleOutputDir = './wwwroot/dist';
    const sharedConfig = {
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: ['.js', '.ts'] },
        output: {
            filename: '[name].js',
            publicPath: '/dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
        },
        module: {
            rules: [
                isDevBuild
                    ? { test: /\.ts$/, include: /ClientApp/, use: ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] }
                    : {
                        test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
                        include: /ClientApp/,
                        loader: '@ngtools/webpack'
                    },
                { test: /\.html$/, use: [{ loader: 'html-loader' }] },
                { test: /\.css$/, use: ['to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize'] },
                { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' },
                {
                    test: /\.scss$/,
                    exclude: /node_modules/,
                    use: ['raw-loader', isDevBuild ? 'sass-loader' : 'sass-loader?minimize'] // sass-loader
                }
            ]
        },
        plugins: [
            new CheckerPlugin()
        ].concat(isDevBuild
            ? // Plugins that apply in development builds only
            [
                new webpack.SourceMapDevToolPlugin({
                    filename: isTest ? null : '[file].map',
                    test: /\.(ts|js)($|\?)/i,
                    moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]')
                })
            ] : [// Plugins that apply in production builds only
            ])
    };

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleConfig = merge(sharedConfig, {
        entry: {
            'main-client': './ClientApp/boot-client.ts'
        },
        output: {
            path: path.join(__dirname, clientBundleOutputDir)
        },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [] : [
            new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.client#AppModule'),
                exclude: ['./**/*.server.ts']
            }),
            new webpack.optimize.UglifyJsPlugin({
                output: {
                    ascii_only: true,
                }
            })])
    });

    const serverBundleConfig = merge(sharedConfig, {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot-server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ].concat(isDevBuild ? [] : [
            new webpack.optimize.UglifyJsPlugin({
                mangle: false,
                compress: false,
                output: {
                    ascii_only: true,
                }
            }),
            new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.server#AppModule'),
                exclude: ['./**/*.client.ts']
            })]),
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },
        target: 'node',
        devtool: isDevBuild || isTest ? 'inline-source-map' : false
    });


    return [clientBundleConfig, serverBundleConfig];
};
```
